sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
env:
  - CXX=g++-4.8
  - NODE_ENV=development
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

before_install:
  - sudo apt-get -y install python3-pip python-dev
  - npm install -g typescript

script:
  - npm run compile

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git push origin master

branches:
  except:
    - master

