version: "3"

services:
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    restart: always
  discord-bot:
    depends_on:
      - redis
    build: .
    volumes:
      - /home/pi/prod/discord/assets:/app/assets
    restart: always
    environment:
      - NODE_ENV=production
      - DiscordBot_redis_server=redis
      - DiscordBot_redis_port=6379
      - DiscordBot_cacheTimeout=86400
      - DiscordBot_aleksa_server_port=5000
      - DiscordBot_server_port=5010
    ports:
      - "5000:5000"
      - "5010:5010"
    container_name: discord-bot

volumes:
  redis_data:
    

